// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OstaniStudent.Database.Models
{
    public partial class Moduli
    {
        public Moduli()
        {
            KorisnikZeljeniModuls = new HashSet<KorisnikZeljeniModul>();
            Predmetis = new HashSet<Predmeti>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Kratica { get; set; }
        public bool JeAktivan { get; set; }

        public virtual ICollection<KorisnikZeljeniModul> KorisnikZeljeniModuls { get; set; }
        public virtual ICollection<Predmeti> Predmetis { get; set; }
    }
}