// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OstaniStudent.Database.Models
{
    public partial class VKorisniciZeljeniModuli
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int IdKorisnik { get; set; }
        public int IdModul { get; set; }
        public int Rang { get; set; }
        public string Naziv { get; set; }
        public bool JeAktivan { get; set; }
    }
}