// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OstaniStudent.Database.Models
{
    public partial class VKorisniciZeljeniPredmeti
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int IdKorisnik { get; set; }
        public int IdPredmet { get; set; }
        public int Rang { get; set; }
        public int BrojIzbora { get; set; }
        public int? IdModul { get; set; }
        public int? IdSifrarnik { get; set; }
        public string Naziv { get; set; }
        public bool? JeZimski { get; set; }
        public int? Kapacitet { get; set; }
        public bool JeAktivan { get; set; }
        public string Modul { get; set; }
        public string Kratica { get; set; }
    }
}