// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OstaniStudent.Database.Models
{
    public partial class VKorisniciUloge
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Jmbag { get; set; }
        public int? KorisnikId { get; set; }
        public int? UlogaId { get; set; }
        public string Naziv { get; set; }
        public string Email { get; set; }
        public int KorisniciUlogeId { get; set; }
        public string Lozinka { get; set; }
    }
}