// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OstaniStudent.Database.Models
{
    public partial class VOstaniStudent
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Jmbag { get; set; }
        public int KorisnikId { get; set; }
        public int? UlogaId { get; set; }
        public string UlogaNaziv { get; set; }
        public string Email { get; set; }
        public int? ModuliId { get; set; }
        public string ModulNaziv { get; set; }
        public int? KorZeljModRang { get; set; }
        public int? KorPredRang { get; set; }
        public int? BrojIzbora { get; set; }
        public int? PredmetId { get; set; }
        public int? IdSifrarnik { get; set; }
        public int? Kapacitet { get; set; }
        public string PredmetNaziv { get; set; }
        public bool JeAktivan { get; set; }
    }
}